all:
  hosts:
    dev1:
      ansible_host: 213.171.29.202
  vars:
    admin_users:
      - name: admin
        password: "{{ vault_admin_pass }}"
        shell: /bin/bash
        sudo: true
        ssh_key: "https://github.com/rootadmin.keys"
    developer_users:
      - name: dev1
        password: "{{ vault_dev1_pass }}"
        shell: /bin/sh
        sudo: false
        ssh_key: "ssh-rsa AAAAB3..."
  children:
    dev_servers:
      hosts:
        dev1:
          remove_users:
            - dev1
          developer_users:
            - name: dev2
              password: "{{ vault_dev2_pass }}"
              shell: /bin/bash
              sudo: false
