all:
  hosts:
    dev1:
      ansible_host: 213.171.29.202
  vars:
    admin_users:
      - name: user1
        password: "{{ user_admin_pass }}"
        shell: /bin/bash
        sudo: true
        ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICI+mr6/4EL7f6Ejt1zx2lRZxeCF+44W9RMYn8qtEjWf pc@DESKTOP-QE8MA6F"
      - name: admin
        password: "{{ user_admin_pass }}"
        shell: /bin/bash
        sudo: true
        ssh_key: "https://github.com/NickGlebanov.keys"
    developer_users:
      - name: dev1
        password: "{{ user_dev1_pass }}"
        shell: /bin/sh
        sudo: false
  children:
    dev_servers:
      hosts:
        dev1:
          remove_users:
            - name: dev1
          developer_users:
            - name: dev2
              password: "{{ user_dev2_pass }}"
              shell: /bin/bash
              sudo: false
