---
- name: Get current system users
  command: getent passwd
  register: passwd_output

- name: Remove unmanaged users
  user:
    name: "{{ item }}"
    state: absent
  loop: "{{ passwd_output.stdout_lines | map('split', ':') | map('first') | difference(users | map(attribute='name') | list + ['root']) }}"
