---
- name: Union users
  set_fact:
    final_users: >-
      {{
        (admin_users + developer_users)
        | rejectattr('name', 'in', remove_users | map(attribute='name') | list)
        | list
      }}
  tags:
    - create_groups
    - create_users
    - sudo_setup
    - cleanup
    - expire_check

- name: Print final users
  debug:
    msg: "users final: \n {{ final_users }} \n ------------------------------"


- name: Include group creation
  include_tasks:
    file: groups.yml
    apply:
      tags:
        - create_groups
  tags: [create_groups]

- name: Include user creation
  include_tasks:
    file: users.yml
    apply:
      tags:
        - create_users
  tags: [create_users]

- name: Include sudoers setup
  include_tasks:
    file: sudo.yml
    apply:
      tags:
        - sudo_setup
  tags: [sudo_setup]


- name: Include expire check
  include_tasks:
    file: expire.yml
    apply:
      tags:
        - expire_check
  tags: [expire_check]
