---
- name: Include group creation
  include_tasks:
    file: groups.yml
    apply:
      tags:
        - create_groups
  tags: [create_groups]

- name: Include user creation
  include_tasks:
    file: users.yml
    apply:
      tags:
        - create_users
  tags: [create_users]

- name: Include sudoers setup
  include_tasks:
    file: sudo.yml
    apply:
      tags:
        - sudo_setup
  tags: [sudo_setup]

- name: Include cleanup of users
  include_tasks:
    file: cleanup.yml
    apply:
      tags:
        - cleanup
  tags: [cleanup]

- name: Include expire check
  include_tasks:
    file: expire.yml
    apply:
      tags:
        - expire_check
  tags: [expire_check]
